spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: test
      secret-key: test
      oss:
        endpoint: test
        bucket: test
  application:
    name: gmail-third-party
server:
  port: 3000
