spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
   3 alicloud:
   #  access-key: 
     # secret-key: 
     # oss:
    #    endpoint: 
     #   bucket: 
  application:
    name: gmail-third-party
server:
  port: 3000
