spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
     access-key: ##
     secret-key: ##
     oss:
       endpoint: oss-cn-shanghai.aliyuncs.com
       bucket: gmail-ygao

  application:
    name: gmail-third-party
server:
  port: 3000
