spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://baidu.com
          predicates:
            - Query=url,baidu
        - id: test_route
          uri: https://qq.com
          predicates:
            - Query=url,qq
        - id: product_route
          uri: lb://gmail-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
        - id: third_party_route
          uri: lb://gmail-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}
        - id: member_route
          uri: lb://gmail-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
        - id: ware_route
          uri: lb://gmail-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}
        - id: gulimall_host_route
          uri: lb://gmail-product
          predicates:
            - Host=**.gulimall.com

